version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile

  mqttbroker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf


